### ISSUE TITLE
Invalid 'main' field

### ISSUE THREAD

**Issue by diegoapajuelo** [mvanderkamp/westures#20]
Hi!

Was writing a program in WAMS, this completely breaks it:

(node:3208) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Users\x\Desktop\Dev\demo\node_modules\westures\core\package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:3208) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Users\x\Desktop\Dev\demo\node_modules\westures\core\package.json' of 'dist/index.js'. Please either fix that or report it to the module author

Node 20.5.0

**Comment by diegoapajuelo** [comment]
Solved eintegrity error. Disregard.

**Comment by mvanderkamp** [comment]
Yup that's my bad. Sorry!

~For now, can you try importing this way instead? Might break you build process though if you're not transpiling dependencies~ :(
```javascript
// nevermind, I don't think this is right
// const westures = require('westures/index');
```

**Comment by mvanderkamp** [comment]
Can you provide more details, re: "completely breaks it"? This is just a deprecation warning. How are you importing `westures`?

I'm tinkering and I see that using `require('westures/index')` triggers this deprecation warning, but `require('westures')` does not. However... for some reason the build doesn't seem to be up to date with the latest release. I might need to fix this with tooling to build the bundle on release, instead of including the build in the git repo...

---

Looking at this from a Node perspective, I apparently should use `exports` instead:
- https://nodejs.org/api/packages.html#main-entry-point-export
- https://nodejs.org/api/packages.html#package-entry-points

Defining `exports` might be enough to fix this. Or perhaps pointing it directly to `index.js` would work, except that `parcel` uses `"main"` to determine where to output the build: https://parceljs.org/getting-started/library/#project-setup

:thinking:

**Comment by diegoapajuelo** [comment]
Still getting the deprecation error, however it's now functional.

Previously that nuked all westure gestures (tongue twister) from functioning.

I imported westures via WAMS, not directly:
`const WAMS = require("wams");
const path = require("node:path");
'

Now to work on server-client messaging...

**Comment by mvanderkamp** [comment]
Poking around at all the issues on github related to this error message, none of them linked to the actual docs on the deprecation, so here it is: https://nodejs.org/api/deprecations.html#dep0128-modules-with-an-invalid-main-entry-and-an-indexjs-file

**Comment by mvanderkamp** [comment]
Oh! I think I know what's happening!

Doing this: `require('westures/index')`, is broken into two steps: `'westures'` and `'/index'`:
1. Looks up the "main" for `'westures'`, which is `'dist/index.js'`
2. Then tries to append `'/index'` giving `'dist/index.js/index'`, which doesn't exist. So node falls back to `'index.js'`, which does exist, but is deprecated behaviour, hence the warning.

Well wasn't that confusing. Okay so the real problem is that the build for the latest release didn't stick, because the correct thing to do is just `require('westures')`

**Comment by mvanderkamp** [comment]
Okay, real resolution, until I have a fixed build out:

```bash
cd node_modules/westures
npm run build
```

You might have to `npm install parcel`, I can't remember if it auto-downloads it in this case or if I'm thinking of a different tool.

Once that's done, rebuild your project that's using westures.

**Comment by diegoapajuelo** [comment]
It doesn't auto download.

Feel free to close this when the build is pushed.

-Diego

**Comment by mvanderkamp** [comment]
Can you try bumping to version `1.1.1`? It should be fixed.

**Comment by diegoapajuelo** [comment]
Bumped.

Deprecation warning gone.
